name: CI with Gradle

on:
  pull_request:
    branches:
      - develop

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Make application.yml
        shell: bash
        env:
          APP_B64: ${{ secrets.PROPERTIES}}
          GOOGLE_JSON: ${{ secrets.GOOGLE_JSON }}
        run: |
          mkdir -p src/main/resources
          echo "$APP_B64" | base64 --decode > src/main/resources/application.yml
          echo "$GOOGLE_JSON" > src/main/resources/firebase-service-account.json

      - name: Run tests
        run: |
          ./gradlew test
