name: CI with Gradle

on:
  pull_request:
    branches:
      - develop

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Make application.yml
        shell: bash
        env:
          APP_YML: ${{ secrets.TEST_PROPERTIES }}   # 그대로 환경변수로
        run: |
          mkdir -p src/main/resources
          printf '%s\n' "$APP_YML" > src/main/resources/application.yml

      - name: Run tests
        run: |
          ./gradlew test
